version: '3'
services:
  mage:
    image: mageai/mageai:latest
    container_name: magic
    depends_on:
      - postgres
    command: mage start magic
    # env_file:
    #   - .env
    environment:
      ENV: dev
      POSTGRES_DB: mage
      POSTGRES_USER: mage
      POSTGRES_PASSWORD: mage123!
      POSTGRES_HOST: localhost
      PG_HOST_PORT: 2345
    ports:
      - 6789:6789
    volumes:
      - /data/mage-workflow/mage_data:/home/src/
    restart: on-failure:5
  
  postgres:
    image: postgres:15
    container_name: postgres-magic
    build:
      context: ./db
    # env_file:
    #   - .env
    environment:
      POSTGRES_DB: mage
      POSTGRES_USER: mage
      POSTGRES_PASSWORD: mage123!
    ports:
      - 2345:5432
    volumes:
      - /data/mage-workflow/postgres_data:/var/lib/postgresql/data
    restart: on-failure:5
